=== msayson/validate_detection_rule_json_cli/resources/request_allow_list_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": {
            "description": "Unique identifier for the request allow-list",
            "type": "string"
        },
        "description": {
            "description": "Description of the request allow-list",
            "type": "string"
        },
        "allowedApiMethods": {
            "description": "Allow-listed API methods",
            "type": "array",
            "items": {
                "$ref": "#/$defs/allowedApiMethod"
            }
        },
        "allowedCliCommands": {
            "description": "Allow-listed CLI commands",
            "type": "array",
            "items": {
                "$ref": "#/$defs/allowedCliCommand"
            }
        }
    },
    "required": [
        "id"
    ],
    "additionalProperties": false,
    "$defs": {
        "allowedApiMethod": {
            "description": "An allow-listed API method",
            "type": "object",
            "properties": {
                "method": {
                    "type": "string",
                    "enum": [
                        "GET",
                        "POST",
                        "PUT",
                        "DELETE"
                    ]
                },
                "url": {
                    "type": "string"
                },
                "allowedHeaderValues": {
                    "description": "Allow-listed header values",
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/allowedValuesForHeader"
                    }
                },
                "description": {
                    "description": "Description of the API method",
                    "type": "string"
                }
            },
            "required": [
                "method",
                "url"
            ],
            "additionalProperties": false
        },
        "allowedCliCommand": {
            "description": "An allow-listed CLI command",
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "exactArgs": {
                    "description": "Exact list of arguments to match (exclusive)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "initialArgs": {
                    "description": "Initial arguments to match (followed by any other arguments)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "Description of the allowed CLI command",
                    "type": "string"
                }
            },
            "required": [
                "command"
            ],
            "additionalProperties": false,
            "anyOf": [
                {
                    "required": [
                        "exactArgs"
                    ],
                    "not": {
                        "required": [
                            "initialArgs"
                        ]
                    }
                },
                {
                    "required": [
                        "initialArgs"
                    ],
                    "not": {
                        "required": [
                            "exactArgs"
                        ]
                    }
                },
                {
                    "not": {
                        "required": [
                            "exactArgs",
                            "initialArgs"
                        ]
                    }
                }
            ]
        },
        "allowedValuesForHeader": {
            "description": "Allow-listed values for a specific header",
            "type": "object",
            "properties": {
                "header": {
                    "type": "string"
                },
                "allowedValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "header",
                "allowedValues"
            ],
            "additionalProperties": false
        }
    }
}

=== msayson/validate_detection_rule_json_cli/resources/test/valid_request_allow_lists/multiple_request_types_allow_list.json
{
    "id": "Test::MultipleRequestTypesAllowList",
    "description": "This is a test request allow-list for API and CLI requests.",
    "allowedCliCommands": [
        {
            "command": "echo"
        },
        {
            "command": "aws",
            "exactArgs": [
                "s3",
                "ls",
                "--region eu-west-2",
                "--profile test-aws-detector"
            ]
        },
        {
            "command": "aws",
            "initialArgs": [
                "dynamodb",
                "list-tables"
            ]
        }
    ],
    "allowedApiMethods": [
        {
            "method": "POST",
            "url": "https://dynamodb.eu-west-2.amazonaws.com",
            "allowedHeaderValues": [
                {
                    "header": "X-Amz-Target",
                    "allowedValues": [
                        "DynamoDB_20120810.DescribeContinuousBackups"
                    ]
                }
            ]
        }
    ]
}
